# Q1

In [1]:
#Creat a numpy array starting from 2 till 50 with a stepsize of 3
import numpy as np
np.arange(start=2,stop=50,step=3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

# Q2

In [3]:
import numpy as np
# Empty list
lst_1 = []
lst_2 = []
# list 1 values
for i in range(5):
 x=int(input("\nEnter values for lst_1 : "))
 lst_1.append(x)

# List 2 values
for i in range(5):
 x=int(input("\nEnter values for lst_2 : "))
 lst_2.append(x)

# Converting list into array
arr_1 = np.array(lst_1)
arr_2 = np.array(lst_2)
# Concatenate to numpy array
arr = (np.concatenate((arr_1, arr_2), axis=0))
print("\nValue for concatenate arr :",arr)
# Sort the arrays and print
sortArr = (np.sort(arr))
print("\nSorted the arrays for concatenated arr :",sortArr)


Enter values for lst_1 : 85

Enter values for lst_1 : 69

Enter values for lst_1 : 65

Enter values for lst_1 : 69

Enter values for lst_1 : 68

Enter values for lst_2 : 89

Enter values for lst_2 : 69

Enter values for lst_2 : 96

Enter values for lst_2 : 69

Enter values for lst_2 : 69

Value for concatenate arr : [85 69 65 69 68 89 69 96 69 69]

Sorted the arrays for concatenated arr : [65 68 69 69 69 69 69 85 89 96]


# Q3

In [7]:
import numpy as np
#Creat nd  array
arr = np.array( [ [1,2,3] , [1,5,6] , [69,66,69]] )
# print dimensions of array (axes)
print("\nDimensions in array : ", arr.ndim)
#print size of array
print("\nSize of array : ", arr.size)



Dimensions in array :  2

Size of array :  9


# Q4

In [8]:
arr = np.arange(8)
print("\nShape of Array : ", arr.shape)
row_arr = arr[np.newaxis, :]
print("\nShape of 2D Array in row : ", row_arr.shape)
col_arr = arr[np.newaxis, :]
print("\nShape of 2D Array in Column : ", col_arr.shape)


Shape of Array :  (8,)

Shape of 2D Array in row :  (1, 8)

Shape of 2D Array in Column :  (1, 8)


# Q5

In [9]:
import numpy as np
arr_1 = np.array([2,3,4,5])
arr_2 = np.array([6,7,8,9])
# Stack and print
print("\nHorizontal :" , np.hstack((arr_1, arr_2)))
print("\nVertical :" , np.vstack((arr_1, arr_2)))



Horizontal : [2 3 4 5 6 7 8 9]

Vertical : [[2 3 4 5]
 [6 7 8 9]]


# Q6

In [11]:
import numpy as np
list = [1,2,4,6,4,8,7,8,3]
print("The unique value from list: ")
print(np.unique(list))

The unique value from list: 
[1 2 3 4 6 7 8]
